### PR TITLE
Fix: lib compilation 

### PR DESCRIPTION
**Pull request by dimartiro**
Change the way we compile lib to include all required types

- Remove not required `scripts/typegen.sh`
- Lint `tsconfig.js`
- Put all declarations in `/lib`

This solve this [issue](https://github.com/ExodusMovement/exodus-web3/pull/780#pullrequestreview-2104463755)

### CODE REVIEW

**Review by kewde — CHANGES_REQUESTED** [review]
Don't change the yarn lock file if possible.

**Comment by dimartiro** [comment]
> Don't change the yarn lock file if possible.

I reverted that file, thanks for the feedback @kewde

**Review by bulgakovk — COMMENTED** [review]
>not required scripts/typegen.sh

Could you explain why it's not required? It would make me feel much safer if we narrowed down the `error TS2306: File '/Users/kb/projects/exodus-web3/node_modules/@exodus/solana-web3.js/lib/index.d.ts' is not a module` error to a certain line(s) to make a fix in the typegen.sh instead.

I compared `build` outputs and the only notable change is that we include declaration files in this branch, is that everything we need to fix the error?

**Comment by dimartiro** [comment]
> Could you explain why it's not required? It would make me feel much safer if we narrowed down the `error TS2306: File '/Users/kb/projects/exodus-web3/node_modules/@exodus/solana-web3.js/lib/index.d.ts' is not a module` error to a certain line(s) to make a fix in the typegen.sh instead.
> 
> I compared `build` outputs and the only notable change is that we include declaration files in this branch, is that everything we need to fix the error?

thanks for the comment @bulgakovk , basically what `typegen.sh` was doing is 'moving' / 'modifying' some files in `/lib` based on what we generated in `/declarations`. 
What I did was to stop using the `/declarations` folder an generate everything in `/lib`.
Certainly this fixes the issue, I'm using a version published with this fix in my original [PR](https://github.com/ExodusMovement/exodus-web3/pull/780) and all tests are passing now.
But I'm not an expert in typescript 😅 so I'm 100% open to suggestions if there is a simpler way to solve it

**Review by bulgakovk — APPROVED** [review]
utACK

The published diff looks huge but it only decouples `index.d.ts` into multiple separate files

**Review by kewde — APPROVED** [review]
utACK

**Comment by bulgakovk** [comment]
@dimartiro Can you take care of releasing this one?

**Comment by dimartiro** [comment]
Sure!

**Pull request merged**
