### PR TITLE
feat: rebase upstream; extend connection class to accept external providers

### PR DESCRIPTION
**Pull request by iamcrazycoder**
## Summary

This PR rebases the upstream master branch and extends the connection class to accept external providers. 

Initially, we tried to apply a [monkey-patch solution](https://github.com/ExodusMovement/solana-web3-adapter) by wrapping the internal func `_rpcRequest` with our implementation to route the requests to our provider. However, after discussing the solution - we decided to apply similar changes to our fork of solana-web3.js as the previous solution was not beneficial for the long term. 

Instead, we updated the Connection class constructor and extended it to accept the `sendAsync` prop in `ConnectionConfig`-  2nd param. Please refer to [this commit](https://github.com/ExodusMovement/solana-web3.js/commit/49ec6c0d94b48ad5eaabd3fe481ac78ec0f0a18e) to review the provider related changes.

@kklash @roccomuso This repo was 669 commits behind the upstream master branch and rebasing it manually was quite a task so I rebased with a flag that accepted remote changes by default. Here's the command that I used: 

```bash
nishant@Nishants-MacBook-Pro solana-web3.js % git rebase upstream/master -s ours
dropping be1b2b65f8415c71c522bbc6cb6d7e743e3861f9 rename package -- patch contents already upstream
dropping 60addd6dd2f1ab0fb66973a086269ea5801100d2 remove build step -- patch contents already upstream
dropping a31560615b0aa91992057dbb9d6c4d5398237191 cleanup -- patch contents already upstream
dropping ed1815b6bfda7f85723494613bff6147934c9fdb "0.1.0-exodus0" -- patch contents already upstream
dropping a2c59e46beae556a9772333ace1b38c49832e003 use babel to compile and publish source -- patch contents already upstream
dropping bab118a201ac9430fc03cc151cf619f9a756a18a 0.87.1-exodus0 -- patch contents already upstream
dropping c6123d79ef9a20d70892d2af31fea98c390cdf58 remove bin folder from tarballs -- patch contents already upstream
dropping e62a579907d774fffe7d282b29ce70ef6aae1ae2 0.87.1-exodus1 -- patch contents already upstream
dropping 7752a4a705e6a034b69673e37a982f0936462d5d remove transform-runtime dep -- patch contents already upstream
dropping a7d57171c95c42f2bf791ad44b519ab743671117 replace jayson with @exodus/json-rpc to reduce dependency bloat -- patch contents already upstream
dropping 63a80740f8e18348a92e628bfa63a7b83b75095a 0.87.1-exodus2 -- patch contents already upstream
dropping 9b7ba790a0207d59addc350277fe47882fcbc55f use exodus fork of buffer-layout -- patch contents already upstream
dropping cbc506f6363be1a55d7a6d4c827052d07d49e77e 0.87.1-exodus3 -- patch contents already upstream
dropping 82a9bbc1d200ed7ba296a4e1f4861d606dc798f9 use sync crypto sha256 -- patch contents already upstream
dropping 44daaa7452128fc03b835dfad51e6b6021488729 0.87.1-exodus4 -- patch contents already upstream
dropping deb1baad8c2a3db0d52ebe78ae87eb1f6a055677 replace crypto with crypto-hash -- patch contents already upstream
dropping 37a177abf4cfe6a77579bb398f685c111c6b692b 0.87.1-exodus4.1 -- patch contents already upstream
Successfully rebased and updated refs/heads/nishant/test-rebase.
```

I have replaced the package name from `@solana/web3.js` to `@exodus/solana-web3.js` but I am not sure which of the above _dropped commits_ I should cherry-pick or leave. Could you guys please help me with this?

## Post merge:
- [ ] Update released version in https://github.com/ExodusMovement/web-dapps/pull/14

### CODE REVIEW

**Comment by kklash** [comment]
@iamcrazycoder This PR has quite a few conflicts with `master`, there's no way for us to neatly merge it. 

This branch seems to be missing our commit history on `master`, including many changes, such as this: deb1baad8c2a3db0d52ebe78ae87eb1f6a055677 and this: 82a9bbc1d200ed7ba296a4e1f4861d606dc798f9

@iamcrazycoder You may need to redo this, because discarding local changes automatically in a rebase will result in losing the changes which we forked this package for in the first place. 

Maintaining git tags should also be considered - if we want to pull in changes from upstream, perhaps we shouldn't be using force pushes, but instead applying the changes from upstream as a single squash-merged commit. We probably shouldn't attempt to derive the desired resulting git tree using that method, it would probably be extremely painful. But that's how we should try to format the resulting change in this repository's git history. 

My suggested approach would be to
1. Create and checkout a fresh branch 
1. `git reset --hard origin/master` 
1. Do an interactive rebase to squash all commits after be1b2b65f8415c71c522bbc6cb6d7e743e3861f9 into one change. This will make cherry-picking easier later.
1. Create and checkout another new branch
1. `git reset --hard upstream/master`
1. `git cherry-pick` the commit you squashed in step (3)
1. resolve conflicts as needed. Possibly you may need to re-implement some code from `origin/master` by hand if upstream changed significantly 
1. `git reset origin/master`
1. `git add . && git commit -m 'pull in changes from upstream'`

The end result is that you've crafted a commit which both pulls in the changes from upstream and also fixes the conflicts with our existing changes. 

This is a very challenging rebase for anyone who's not highly familiar with git - don't be afraid to ask for help in slack channels here, @iamcrazycoder ! :+1:  Let's keep the rebase with upstream, and the Connection class changes (for dapps) separate, as they are distinct issues. 

Another option we could consider: is the upstream rebase needed for any reason? Why are we trying to pull in changes from upstream in the first place? OP does not mention the motivation behind that.

**Comment by iamcrazycoder** [comment]
@kklash I knew it was going to be a challenging rebase. I tried doing it anyway but looks like it excluded the important changes done by you and Rocco. 

Thank you for the detailed step-by-step guide to handle a complex rebase. I will try this locally and see how it works, and I will ask for help on Slack whenever I am stuck or confused. :) 

> is the upstream rebase needed for any reason?

@kklash There was no strong reason to rebase the upstream branch. Just a common thought of keeping this repo up-to-date with the latest changes was the primary reason. What do you suggest in this case? I would like to defer the decision to you since you have more understanding of this project. (I will still try to rebase the upstream _locally_ - just for my knowledge.)

**Comment by kklash** [comment]
> Just a common thought of keeping this repo up-to-date with the latest changes was the primary reason. What do you suggest in this case? I would like to defer the decision to you since you have more understanding of this project. (I will still try to rebase the upstream locally - just for my knowledge.)

I think that's reasonable, would love to know what @roccomuso thinks.

**Comment by roccomuso** [comment]
We had the same rebasing issue with hedera some months ago, keeping up with the updates requires a lot of time.
You guys are using this repo more than I do. I leave the choices up to you.
Just bear in mind that it is an actively maintained package and so this rebase will be needed again a few months from now.

**Comment by iamcrazycoder** [comment]
Closing this PR in favour of https://github.com/ExodusMovement/solana-web3.js/pull/2

**Pull request closed without merging**
