### PR TITLE
refactor(rebase): pull in changes from upstream master

### PR DESCRIPTION
**Pull request by iamcrazycoder**
This PR rebases the [upstream](https://github.com/solana-labs/solana-web3.js) master branch on our fork of solana-web3.js. We initially attempted to rebase in https://github.com/ExodusMovement/solana-web3.js/pull/1. However, the approach was incorrect, and @kklash suggested the same be done in a better way in this [comment](https://github.com/ExodusMovement/solana-web3.js/pull/1#issuecomment-1011460997). 

Somewhere between the current `origin/master` and `upstream/master`, all js files were converted to typescript (.ts) files thus making the rebase process complicated. Few changes that were made in our fork had to be moved to the relevant typescript file. Here's a quick comparison of a couple of files:

| File | Current changes | New changes | Dropped changes |
| :-:   | :-: | :---: | :-: |
| connection.js to connection.ts | https://github.com/ExodusMovement/solana-web3.js/commit/a7d57171c95c42f2bf791ad44b519ab743671117 | - [replace jayson with @exodus/json-rpc](https://github.com/ExodusMovement/solana-web3.js/blob/nishant/rebase-upstream-master/src/connection.ts#L25-L26)<br/><br/>- [replace jayson client with RPC](https://github.com/ExodusMovement/solana-web3.js/blob/nishant/rebase-upstream-master/src/connection.ts#L786-L866) | - [Conversion](https://github.com/ExodusMovement/solana-web3.js/commit/a7d57171c95c42f2bf791ad44b519ab743671117#diff-c0232d26030287bbc71fcffcbfa9f00761a1b02865eb9adda7fb81a71161b8a3L629-R620) of id to number type.<br/> Dropped this change since js-sdk already returns id in string type <br/> refer https://github.com/ExodusMovement/exodus-javascript-sdk/pull/58|
| publickey.js to publickey.ts | https://github.com/ExodusMovement/solana-web3.js/commit/82a9bbc1d200ed7ba296a4e1f4861d606dc798f9 | - [replace `async sha256` with `sync createHash`](https://github.com/ExodusMovement/solana-web3.js/commit/3c3cef0a1adc34c89cc6e87adf1e3feba91df5cb#diff-a727740b297a1121a964a2115ffbd0c602b1b959992f235c3b12b85f7380970aR160-R178) | - |

This PR includes changes that are breaking because of the missing type declarations for @exodus/json-rpc and create-hash package. Also, the node polyfills needs to be installed and configured in rollup config to use `events` on the browser side.

_Dependent PRs will linked here shortly._

- [ ] Update released version in [feat: add SolanaContext web-dapps#14](https://github.com/ExodusMovement/web-dapps/pull/14)

### CODE REVIEW

**Comment by kklash** [comment]
@iamcrazycoder exactly which upstream commit did you pull changes in from? Knowing which upstream commit we are using makes it easy to compare this branch with upstream, and also is great for posterity, because then we can know which commits to pull in, in the future.

I believe it was https://github.com/solana-labs/solana-web3.js/commits/03268b698a180ecb14c9a4b5c255d8f1c434e69b but i would like to be 100% sure

**Comment by iamcrazycoder** [comment]
@kklash You're right. Pulled in changes from the master branch of the upstream repo. During the rebase, **feat: add Connection.getFeeForMessage** was the latest commit.

**Comment by kklash** [comment]
<details>
<summary>For those interested, here's a diff of this branch against the upstream commit Nishant rebased on (package-lock.json ignored)</summary>

```diff
diff --git a/package.json b/package.json
index 43845fb..42cef0d 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
-  "name": "@solana/web3.js",
-  "version": "0.0.0-development",
+  "name": "@exodus/solana-web3.js",
+  "version": "0.87.1-exodus4.1",
   "description": "Solana Javascript API",
   "keywords": [
     "api",
@@ -11,10 +11,10 @@
   "homepage": "https://solana.com/",
   "repository": {
     "type": "git",
-    "url": "https://github.com/solana-labs/solana-web3.js.git"
+    "url": "https://github.com/ExodusMovement/solana-web3.js.git"
   },
   "bugs": {
-    "url": "http://github.com/solana-labs/solana-web3.js.git/issues"
+    "url": "http://github.com/ExodusMovement/solana-web3.js.git/issues"
   },
   "publishConfig": {
     "access": "public"
@@ -23,8 +23,8 @@
     "./lib/index.cjs.js": "./lib/index.browser.esm.js",
     "./lib/index.esm.js": "./lib/index.browser.esm.js"
   },
-  "main": "lib/index.cjs.js",
-  "module": "lib/index.esm.js",
+  "main": "lib/index.browser.esm.js",
+  "module": "lib/index.browser.esm.js",
   "types": "lib/index.d.ts",
   "browserslist": [
     "defaults",
@@ -33,8 +33,7 @@
   ],
   "files": [
     "/lib",
-    "/module.flow.js",
-    "/src"
+    "/module.flow.js"
   ],
   "scripts": {
     "build": "npm run clean; cross-env NODE_ENV=production rollup -c; npm run type:gen; npm run flow:gen; npm run flow:check",
@@ -51,7 +50,7 @@
     "ok": "run-s lint test doc",
     "pretty": "prettier --check '{,{src,test}/**/}*.{j,t}s'",
     "pretty:fix": "prettier --write '{,{src,test}/**/}*.{j,t}s'",
-    "re": "semantic-release --repository-url git@github.com:solana-labs/solana-web3.js.git",
+    "re": "semantic-release --repository-url git@github.com:ExodusMovement/solana-web3.js.git",
     "test": "mocha -r ts-node/register './test/**/*.test.ts'",
     "test:cover": "TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' nyc --reporter=lcov mocha -r ts-node/register './test/**/*.test.ts'",
     "test:live": "TEST_LIVE=1 npm run test",
@@ -65,8 +64,9 @@
     "borsh": "^0.4.0",
     "bs58": "^4.0.1",
     "buffer": "6.0.1",
+    "create-hash": "~1.1.3",
     "cross-fetch": "^3.1.4",
-    "jayson": "^3.4.4",
+    "@exodus/json-rpc": "^1.6.0",
     "js-sha3": "^0.8.0",
     "rpc-websockets": "^7.4.2",
     "secp256k1": "^4.0.2",
diff --git a/src/connection.ts b/src/connection.ts
index 0f9b788..0035120 100644
--- a/src/connection.ts
+++ b/src/connection.ts
@@ -22,7 +22,8 @@ import {
 } from 'superstruct';
 import type {Struct} from 'superstruct';
 import {Client as RpcWebSocketClient} from 'rpc-websockets';
-import RpcClient from 'jayson/lib/client/browser';
+import RPC from '@exodus/json-rpc';
+import EventEmitter from 'events';
 import {IWSRequestParams} from 'rpc-websockets/dist/lib/client';
 
 import {AgentManager} from './agent-manager';
@@ -755,7 +756,7 @@ function createRpcClient(
   httpHeaders?: HttpHeaders,
   fetchMiddleware?: FetchMiddleware,
   disableRetryOnRateLimit?: boolean,
-): RpcClient {
+): RPC {
   let agentManager: AgentManager | undefined;
   if (!process.env.BROWSER) {
     agentManager = new AgentManager(useHttps);
@@ -782,7 +783,9 @@ function createRpcClient(
     };
   }
 
-  const clientBrowser = new RpcClient(async (request, callback) => {
+  const transport = new EventEmitter()
+  // @ts-ignore
+  transport.write = async(request: any) => {
     const agent = agentManager ? agentManager.requestStart() : undefined;
     const options = {
       method: 'POST',
@@ -826,51 +829,38 @@ function createRpcClient(
 
       const text = await res.text();
       if (res.ok) {
-        callback(null, text);
+        transport.emit('data', text);
       } else {
-        callback(new Error(`${res.status} ${res.statusText}: ${text}`));
+        throw new Error(`${res.status} ${res.statusText}: ${text}`);
       }
     } catch (err) {
-      if (err instanceof Error) callback(err);
+      throw err;
     } finally {
       agentManager && agentManager.requestEnd();
     }
-  }, {});
+  }
 
-  return clientBrowser;
+  const rpc = new RPC({ transport })
+  return rpc;
 }
 
-function createRpcRequest(client: RpcClient): RpcRequest {
-  return (method, args) => {
-    return new Promise((resolve, reject) => {
-      client.request(method, args, (err: any, response: any) => {
-        if (err) {
-          reject(err);
-          return;
-        }
-        resolve(response);
-      });
-    });
-  };
+function createRpcRequest(rpc: RPC): RpcRequest {
+  return (method, args) => rpc.callMethodWithRawResponse(method, args);
 }
 
-function createRpcBatchRequest(client: RpcClient): RpcBatchRequest {
+function createRpcBatchRequest(rpc: RPC): RpcBatchRequest {
   return (requests: RpcParams[]) => {
     return new Promise((resolve, reject) => {
       // Do nothing if requests is empty
       if (requests.length === 0) resolve([]);
 
       const batch = requests.map((params: RpcParams) => {
-        return client.request(params.methodName, params.args);
+        return rpc.callMethodWithRawResponse(params.methodName, params.args);
       });
 
-      client.request(batch, (err: any, response: any) => {
-        if (err) {
-          reject(err);
-          return;
-        }
-        resolve(response);
-      });
+      Promise.all(batch)
+      .then(response => resolve(response))
+      .catch(err => reject(err))
     });
   };
 }
@@ -2018,7 +2008,7 @@ export class Connection {
   /** @internal */ _confirmTransactionInitialTimeout?: number;
   /** @internal */ _rpcEndpoint: string;
   /** @internal */ _rpcWsEndpoint: string;
-  /** @internal */ _rpcClient: RpcClient;
+  /** @internal */ _rpcClient: RPC;
   /** @internal */ _rpcRequest: RpcRequest;
   /** @internal */ _rpcBatchRequest: RpcBatchRequest;
   /** @internal */ _rpcWebSocket: RpcWebSocketClient;
diff --git a/src/publickey.ts b/src/publickey.ts
index cc8b2f8..71bffda 100644
--- a/src/publickey.ts
+++ b/src/publickey.ts
@@ -2,7 +2,7 @@ import BN from 'bn.js';
 import bs58 from 'bs58';
 import {Buffer} from 'buffer';
 import nacl from 'tweetnacl';
-import {sha256} from '@ethersproject/sha2';
+import createHash from 'create-hash';
 
 import {Struct, SOLANA_SCHEMA} from './util/borsh-schema';
 import {toBuffer} from './util/to-buffer';
@@ -124,29 +124,27 @@ export class PublicKey extends Struct {
    * The program ID will also serve as the owner of the public key, giving
    * it permission to write data to the account.
    */
-  /* eslint-disable require-await */
-  static async createWithSeed(
+  static createWithSeed(
     fromPublicKey: PublicKey,
     seed: string,
     programId: PublicKey,
-  ): Promise<PublicKey> {
+  ): PublicKey {
     const buffer = Buffer.concat([
       fromPublicKey.toBuffer(),
       Buffer.from(seed),
       programId.toBuffer(),
     ]);
-    const hash = sha256(new Uint8Array(buffer)).slice(2);
-    return new PublicKey(Buffer.from(hash, 'hex'));
+    const hash = createHash('sha256').update(buffer).digest();
+    return new PublicKey(hash);
   }
 
   /**
    * Derive a program address from seeds and a program ID.
    */
-  /* eslint-disable require-await */
-  static async createProgramAddress(
+  static createProgramAddress(
     seeds: Array<Buffer | Uint8Array>,
     programId: PublicKey,
-  ): Promise<PublicKey> {
+  ): PublicKey {
     let buffer = Buffer.alloc(0);
     seeds.forEach(function (seed) {
       if (seed.length > MAX_SEED_LENGTH) {
@@ -159,7 +157,7 @@ export class PublicKey extends Struct {
       programId.toBuffer(),
       Buffer.from('ProgramDerivedAddress'),
     ]);
-    let hash = sha256(new Uint8Array(buffer)).slice(2);
+    let hash = createHash('sha256').update(buffer).digest('hex');
     let publicKeyBytes = new BN(hash, 16).toArray(undefined, 32);
     if (is_on_curve(publicKeyBytes)) {
       throw new Error(`Invalid seeds, address must fall off the curve`);
@@ -174,16 +172,16 @@ export class PublicKey extends Struct {
    * iterates a nonce until it finds one that when combined with the seeds
    * results in a valid program address.
    */
-  static async findProgramAddress(
+  static findProgramAddress(
     seeds: Array<Buffer | Uint8Array>,
     programId: PublicKey,
-  ): Promise<[PublicKey, number]> {
+  ): [PublicKey, number] {
     let nonce = 255;
     let address;
     while (nonce != 0) {
       try {
         const seedsWithNonce = seeds.concat(Buffer.from([nonce]));
-        address = await this.createProgramAddress(seedsWithNonce, programId);
+        address = this.createProgramAddress(seedsWithNonce, programId);
       } catch (err) {
         if (err instanceof TypeError) {
           throw err;
diff --git a/test/nonce.test.ts b/test/nonce.test.ts
index 81d871d..3e8ed65 100644
--- a/test/nonce.test.ts
+++ b/test/nonce.test.ts
@@ -111,7 +111,7 @@ describe('Nonce', () => {
   it('create and query nonce account with seed', async () => {
     const from = Keypair.generate();
     const seed = 'seed';
-    const noncePubkey = await PublicKey.createWithSeed(
+    const noncePubkey = PublicKey.createWithSeed(
       from.publicKey,
       seed,
       SystemProgram.programId,
diff --git a/test/publickey.test.ts b/test/publickey.test.ts
index d6a725c..16762e1 100644
--- a/test/publickey.test.ts
+++ b/test/publickey.test.ts
@@ -106,9 +106,9 @@ describe('PublicKey', function () {
     expect(key1.equals(key2)).to.be.true;
   });
 
-  it('createWithSeed', async () => {
+  it('createWithSeed', () => {
     const defaultPublicKey = new PublicKey('11111111111111111111111111111111');
-    const derivedKey = await PublicKey.createWithSeed(
+    const derivedKey = PublicKey.createWithSeed(
       defaultPublicKey,
       'limber chicken: 4/45',
       defaultPublicKey,
@@ -121,7 +121,7 @@ describe('PublicKey', function () {
     ).to.be.true;
   });
 
-  it('createProgramAddress', async () => {
+  it('createProgramAddress', () => {
     const programId = new PublicKey(
       'BPFLoader1111111111111111111111111111111111',
     );
@@ -129,7 +129,7 @@ describe('PublicKey', function () {
       'SeedPubey1111111111111111111111111111111111',
     );
 
-    let programAddress = await PublicKey.createProgramAddress(
+    let programAddress = PublicKey.createProgramAddress(
       [Buffer.from('', 'utf8'), Buffer.from([1])],
       programId,
     );
@@ -139,7 +139,7 @@ describe('PublicKey', function () {
       ),
     ).to.be.true;
 
-    programAddress = await PublicKey.createProgramAddress(
+    programAddress = PublicKey.createProgramAddress(
       [Buffer.from('☉', 'utf8')],
       programId,
     );
@@ -149,7 +149,7 @@ describe('PublicKey', function () {
       ),
     ).to.be.true;
 
-    programAddress = await PublicKey.createProgramAddress(
+    programAddress = PublicKey.createProgramAddress(
       [Buffer.from('Talking', 'utf8'), Buffer.from('Squirrels', 'utf8')],
       programId,
     );
@@ -159,7 +159,7 @@ describe('PublicKey', function () {
       ),
     ).to.be.true;
 
-    programAddress = await PublicKey.createProgramAddress(
+    programAddress = PublicKey.createProgramAddress(
       [publicKey.toBuffer()],
       programId,
     );
@@ -169,13 +169,13 @@ describe('PublicKey', function () {
       ),
     ).to.be.true;
 
-    const programAddress2 = await PublicKey.createProgramAddress(
+    const programAddress2 = PublicKey.createProgramAddress(
       [Buffer.from('Talking', 'utf8')],
       programId,
     );
     expect(programAddress.equals(programAddress2)).to.eq(false);
 
-    await expect(
+    expect(
       PublicKey.createProgramAddress(
         [Buffer.alloc(MAX_SEED_LENGTH + 1)],
         programId,
@@ -193,7 +193,7 @@ describe('PublicKey', function () {
       let programId = new PublicKey(
         '4ckmDgGdxQoPDLUkDT3vHgSAkzA3QRdNq5ywwY4sUSJn',
       );
-      programAddress = await PublicKey.createProgramAddress(seeds, programId);
+      programAddress = PublicKey.createProgramAddress(seeds, programId);
       expect(
         programAddress.equals(
           new PublicKey('12rqwuEgBYiGhBrDJStCiqEtzQpTTiZbh7teNVLuYcFA'),
@@ -202,17 +202,17 @@ describe('PublicKey', function () {
     }
   });
 
-  it('findProgramAddress', async () => {
+  it('findProgramAddress', () => {
     const programId = new PublicKey(
       'BPFLoader1111111111111111111111111111111111',
     );
-    let [programAddress, nonce] = await PublicKey.findProgramAddress(
+    let [programAddress, nonce] = PublicKey.findProgramAddress(
       [Buffer.from('', 'utf8')],
       programId,
     );
     expect(
       programAddress.equals(
-        await PublicKey.createProgramAddress(
+        PublicKey.createProgramAddress(
           [Buffer.from('', 'utf8'), Buffer.from([nonce])],
           programId,
         ),
diff --git a/test/stake-program.test.ts b/test/stake-program.test.ts
index 8cf581d..3935001 100644
--- a/test/stake-program.test.ts
+++ b/test/stake-program.test.ts
@@ -21,10 +21,10 @@ import {url} from './url';
 use(chaiAsPromised);
 
 describe('StakeProgram', () => {
-  it('createAccountWithSeed', async () => {
+  it('createAccountWithSeed', () => {
     const fromPubkey = Keypair.generate().publicKey;
     const seed = 'test string';
-    const newAccountPubkey = await PublicKey.createWithSeed(
+    const newAccountPubkey = PublicKey.createWithSeed(
       fromPubkey,
       seed,
       StakeProgram.programId,
@@ -279,10 +279,10 @@ describe('StakeProgram', () => {
     expect(params).to.eql(StakeInstruction.decodeDeactivate(stakeInstruction));
   });
 
-  it('StakeInstructions', async () => {
+  it('StakeInstructions', () => {
     const from = Keypair.generate();
     const seed = 'test string';
-    const newAccountPubkey = await PublicKey.createWithSeed(
+    const newAccountPubkey = PublicKey.createWithSeed(
       from.publicKey,
       seed,
       StakeProgram.programId,
@@ -407,7 +407,7 @@ describe('StakeProgram', () => {
 
       // Create Stake account with seed
       const seed = 'test string';
-      const newAccountPubkey = await PublicKey.createWithSeed(
+      const newAccountPubkey = PublicKey.createWithSeed(
         payer.publicKey,
         seed,
         StakeProgram.programId,
```
</details>

**Review by kklash — APPROVED** [review]
utACK based on diffing with upstream commit `03268b698a180ecb14c9a4b5c255d8f1c434e69b`

**Pull request merged**
